### ISSUE TITLE
Some blocks don't evaluate. Must `M-x eval-r` to initialize. 

### ISSUE THREAD

**Issue by SeaDude** [hrs/dotfiles#41]
I've been having a great time setting up my literate emacs init file using your method. Not sure how to debug a code block that won't initialize during startup though. Here is an example block that I have to run `M-x eval-r` to initialize. Why isn't this "firing" up with the rest of the source blocks in my `config.org` file? 

Any ideas? 
```
* Calfw setup
#+BEGIN_SRC 
(require 'calfw)
(require 'calfw-org)

(defun my-open-calendar ()
  (interactive)
  (cfw:open-calendar-buffer
   :contents-sources
   (list
    (cfw:org-create-source "Green")  ; orgmode source
)))
#+END_SRC
```
Thanks

**Comment by hrs** [comment]
Hi, @SeaDude!

Here's my guess: Org can only evaluate code when it can determine which interpreter to use, but this block doesn't indicate that. Trying changing:

```
#+BEGIN_SRC
```
to
```
#+BEGIN_SRC emacs-lisp
```

Hopefully that'll do the trick!

**Comment by SeaDude** [comment]
Hey hey! Look at that. Now _all_ of those little "things" I just couldn't get working are working! This is right up there with `M-x check-parens`. 

Thanks a bunch. Really appreciate it.
