### ISSUE TITLE
use dotbot instead of install.sh

### ISSUE THREAD

**Issue by rafaelleru** [hrs/dotfiles#43]
it's only a proposal

**Comment by hrs** [comment]
Thanks for the suggestion, @rafaelleru! Dotbot looks like a neat tool.

But I think I'm happy with [`stow`](https://www.gnu.org/software/stow/) for now, and the current [`install.sh`](https://github.com/hrs/dotfiles/blob/master/install.sh) is already pretty simple and easy to maintain.
