### ISSUE TITLE
`hrs/set-font-size` gets 'stuck' for new frames

### ISSUE THREAD

**Issue by rneatherway** [hrs/dotfiles#50]
Hi, I've been trying your font changing functions and found that the font size setting for new frames gets 'stuck'. Because `hrs/set-font-size` uses `(add-to-list 'default-frame-alist (cons 'font font-code))`, if `default-frame-alist` contains that same cell already it won't be prepended again. If you increase and decrease the font size you end up with it having a value such as:

```
((font . "Inconsolata-14")
 (font . "Inconsolata-16"))
```

And then if you increase again, the setting of 16 will not be added and new frames will be size 14, out of sync with existing frames. I am using a local change to use `setcdr` if `'font` is already set:

```lisp
(defun hrs/set-font-size ()
  "Set the font to `hrs/default-font' at `hrs/current-font-size'.
Set that for the current frame, and also make it the default for
other, future frames."
  (let ((font-code (hrs/font-code)))
    (if (assoc 'font default-frame-alist)
        (setcdr (assoc 'font default-frame-alist) font-code)
      (add-to-list 'default-frame-alist (cons 'font font-code)))
    (set-frame-font font-code nil t)))
```

**Comment by hrs** [comment]
Oh, hey, that's a nice fix, @rneatherway! I'd noticed that happening here and there, but I rarely use more than one frame, so I think I wasn't feeling enough pain to seek out a solution. =)

I've just incorporated that diff into my config. Thanks again!

**Comment by rneatherway** [comment]
:+1:
