### ISSUE TITLE
Errors after opening emacs using configuration.org

### ISSUE THREAD

**Issue by m0m0khan** [hrs/dotfiles#54]
Hey,

I am receiving a bunch of errors after opening emacs. I ran "emacs --debug-init". Following are the errors I am having:

`Debugger entered--Lisp error: (error "Font not available" #<font-spec nil nil Inconsolata-11 nil nil nil nil nil nil nil nil nil ((:name . "Inconsolata-11") (:user-spec . "Inconsolata-11"))>)
  internal-set-lisp-face-attribute(default :font "Inconsolata-11" #<frame emacs@khan-Latitude-5491 0x1432c30>)
  set-face-attribute(default #<frame emacs@khan-Latitude-5491 0x1432c30> :width normal :weight normal :slant normal :font "Inconsolata-11")
  set-frame-font("Inconsolata-11")
  (let ((font-code (hrs/font-code))) (if (assoc (quote font) default-frame-alist) (setcdr (assoc (quote font) default-frame-alist) font-code) (add-to-list (quote default-frame-alist) (cons (quote font) font-code))) (set-frame-font font-code))
  hrs/set-font-size()
  hrs/reset-font-size()
  eval-buffer(#<buffer  *load*-23261> nil "/home/khan/Documents/Development/emacs/configuration.el" nil t)  ; Reading at buffer position 6590
  load-with-code-conversion("/home/khan/Documents/Development/emacs/configuration.el" "/home/khan/Documents/Development/emacs/configuration.el" nil nil)
  load("/home/khan/Documents/Development/emacs/configuration.el" nil nil t)
  load-file("~/Documents/Development/emacs/configuration.el")
  org-babel-load-file("~/Documents/Development/emacs/configuration.org")
  eval-buffer(#<buffer  *load*> nil "/home/khan/.emacs" nil t)  ; Reading at buffer position 758
  load-with-code-conversion("/home/khan/.emacs" "/home/khan/.emacs" t t)
  load("~/.emacs" t t)
  #f(compiled-function () #<bytecode 0x25e919>)()
  command-line()
  normal-top-level()`

Can anybody help me here?

Thanks

**Comment by m0m0khan** [comment]
Debugger entered--Lisp error: (error "Font not available" #<font-spec nil nil Inconsolata-11 nil nil nil nil nil nil nil nil nil ((:name . "Inconsolata-11") (:user-spec . "Inconsolata-11"))>)
  internal-set-lisp-face-attribute(default :font "Inconsolata-11" #<frame emacs@khan-Latitude-5491 0x1432c30>)
  set-face-attribute(default #<frame emacs@khan-Latitude-5491 0x1432c30> :width normal :weight normal :slant normal :font "Inconsolata-11")
  set-frame-font("Inconsolata-11")
  (let ((font-code (hrs/font-code))) (if (assoc (quote font) default-frame-alist) (setcdr (assoc (quote font) default-frame-alist) font-code) (add-to-list (quote default-frame-alist) (cons (quote font) font-code))) (set-frame-font font-code))
  hrs/set-font-size()
  hrs/reset-font-size()
  eval-buffer(#<buffer  *load*-805562> nil "/home/khan/Documents/Development/emacs/configuration.el" nil t)  ; Reading at buffer position 6590
  load-with-code-conversion("/home/khan/Documents/Development/emacs/configuration.el" "/home/khan/Documents/Development/emacs/configuration.el" nil nil)
  load("/home/khan/Documents/Development/emacs/configuration.el" nil nil t)
  load-file("~/Documents/Development/emacs/configuration.el")
  org-babel-load-file("~/Documents/Development/emacs/configuration.org")
  eval-buffer(#<buffer  *load*> nil "/home/khan/.emacs" nil t)  ; Reading at buffer position 758
  load-with-code-conversion("/home/khan/.emacs" "/home/khan/.emacs" t t)
  load("~/.emacs" t t)
  #f(compiled-function () #<bytecode 0x25e919>)()
  command-line()
  normal-top-level()

Much readable here!

**Comment by hrs** [comment]
Sorry for the absurdly late response, and I'm sure you've sorted it out by now, but, for posterity, the issue here is that I'm using the font [Inconsolata](https://www.levien.com/type/myfonts/inconsolata.html), which currently needs to be manually installed.
